version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-presupuestos
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  usuarioservice:
    build:
      context: ./usuarioservice
      dockerfile: Dockerfile
    container_name: usuarioservice
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./usuarioservice/.env:/app/.env
    restart: always

volumes:
  postgres-data: