version: "3.8"
services:
  postgres:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 1g
    cpus: 0.5
    ports:
      - "5433:5433"
    command: postgres -c 'port=5433'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    mem_limit: 512m
    cpus: 0.5

  usuarioservice:
    build: ./usuarioservice
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      # solo lo que cambia para este servicio
      - SERVER_PORT=8080
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m
    mem_limit: 512m
    cpus: 0.5

  productoservice:
    build: ./productoservice
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=8082
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m
    mem_limit: 512m
    cpus: 0.5

  negocioservice:
    build: ./negocioservice
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - SERVER_PORT=8081
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m
    mem_limit: 512m
    cpus: 0.5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: presupuestosai-frontend
    ports:
      - "3000:80"
    depends_on:
      - usuarioservice
      - productoservice
      - negocioservice
    mem_limit: 256m
    cpus: 0.25

volumes:
  postgres_data:
